### ISSUE TITLE
OAuth Authorization guide

### ISSUE THREAD

**Issue by khlopkov** [googleapis/java-analytics-data#625]
:bus: This library has moved to
[google-cloud-java/java-analytics-data](
https://github.com/googleapis/google-cloud-java/tree/main/java-analytics-data).
This repository will be archived in the future.

Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Hello

Currently, [your documentation](https://developers.google.com/analytics/devguides/reporting/data/v1/quickstart-client-libraries) contains only the guide for authentication with service account, but there is nothing about OAuth authorization.

 We have an application registered in Google Cloud Platform with a Client ID and Client Secret, and user authorized in our application and having an access and refresh token. How could we get GA4 report for that user using your library?

**Comment by khlopkov** [comment]
Sorry, finally I found out that I need to install google oauth library:

```gradle
    implementation 'com.google.auth:google-auth-library-oauth2-http:1.3.0'
```
 and use `UserCredentials then` in the following way:
```java
FixedCredentialsProvider.create(
     UserCredentials.newBuilder()
                    .setClientId(user.app().clientId())
                    .setClientSecret(user.app().clientSecret())
                    .setAccessToken(userAccessToken)
                    .setRefreshToken(user.refreshToken())
                    .build());
```

IMO, it is not quite obvious that I need to install extra library to use OAuth authentication. Does it make sense for you to add something about that into the documentation? Or maybe I just missing something

**Comment by suztomo** [comment]
Great that you found the solution. This repo has moved to https://github.com/googleapis/google-cloud-java/tree/main/java-analytics-data
